name: remember-brave-people
on:
  pull_request_target:
    branches:
      - master
jobs:
  remember-brave-people:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      - name: Checkout PR branch
        run: |
          git remote add ${{ github.event.pull_request.user.login }} ${{ github.event.pull_request.head.repo.html_url }}
          git fetch ${{ github.event.pull_request.user.login }}
          git checkout -b ${{ github.event.pull_request.user.login }}_${{ github.event.pull_request.head.ref }} ${{ github.event.pull_request.user.login }}/${{ github.event.pull_request.head.ref }}
      - name: Verify 1
        run: bash -e -x ./verify.sh
      - name: Verify 2
        run: bash -e -x ./verify-forkpoint.sh
